#ifndef ADATIVETHRESHOLD_GLOBAL_H
#define ADATIVETHRESHOLD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADATIVETHRESHOLD_LIBRARY)
#  define ADATIVETHRESHOLD_EXPORT Q_DECL_EXPORT
#else
#  define ADATIVETHRESHOLD_EXPORT Q_DECL_IMPORT
#endif

#endif // ADATIVETHRESHOLD_GLOBAL_H
